name: "Build"
on: [release]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          tar -C connector-definition -czvf connector-definition.tgz  model.json .hasura-connector
